// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/account/logout": {
    params: {};
  };
  "/account/signin": {
    params: {};
  };
  "/account/signup": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/projects/new": {
    params: {};
  };
  "/projects/:id": {
    params: {
      "id": string;
    };
  };
  "/settings": {
    params: {};
  };
  "/setup-admin": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/account/logout" | "/account/signin" | "/account/signup" | "/admin" | "/dashboard" | "/projects/new" | "/projects/:id" | "/settings" | "/setup-admin" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./account/logout/page.jsx": {
    id: "account/logout/page";
    page: "/account/logout";
  };
  "./account/signin/page.jsx": {
    id: "account/signin/page";
    page: "/account/signin";
  };
  "./account/signup/page.jsx": {
    id: "account/signup/page";
    page: "/account/signup";
  };
  "./admin/page.jsx": {
    id: "admin/page";
    page: "/admin";
  };
  "./dashboard/page.jsx": {
    id: "dashboard/page";
    page: "/dashboard";
  };
  "./projects/new/page.jsx": {
    id: "projects/new/page";
    page: "/projects/new";
  };
  "./projects/[id]/page.jsx": {
    id: "projects/[id]/page";
    page: "/projects/:id";
  };
  "./settings/page.jsx": {
    id: "settings/page";
    page: "/settings";
  };
  "./setup-admin/page.jsx": {
    id: "setup-admin/page";
    page: "/setup-admin";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "account/logout/page": typeof import("./src/app/./account/logout/page.jsx");
  "account/signin/page": typeof import("./src/app/./account/signin/page.jsx");
  "account/signup/page": typeof import("./src/app/./account/signup/page.jsx");
  "admin/page": typeof import("./src/app/./admin/page.jsx");
  "dashboard/page": typeof import("./src/app/./dashboard/page.jsx");
  "projects/new/page": typeof import("./src/app/./projects/new/page.jsx");
  "projects/[id]/page": typeof import("./src/app/./projects/[id]/page.jsx");
  "settings/page": typeof import("./src/app/./settings/page.jsx");
  "setup-admin/page": typeof import("./src/app/./setup-admin/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};